### ISSUE TITLE
Missing use-package macro package?

### ISSUE THREAD

**Issue by KnutUH** [renzmann/.emacs.d#1]
I'm looking around at various Emacs config's trying improve my setup and learn some..

Read some of your excellent blog-posts and moved away my .emacs.d and cloned your repo to test a little :-)

I'm on mac, running emacs 28.2 had to comment out some fonts and stuff to make Emacs happy, but the most confusing thing was use-package errors and finally I got it working by adding the use-package package to get the use-package macros. Yes, as you said in one of your post use-package is confusing. 

Anyway, you probably do not need this issue, but I wanted to say I enjoyed your blog post ;-) See diff below if you like.

KnutUH

diff --git a/README.org b/README.org
index d3ea0fe..2733028 100644
--- a/README.org
+++ b/README.org
@@ -182,6 +182,13 @@ There are also a few hand-made packages I keep around in a special

 #+begin_src emacs-lisp
   (add-to-list 'load-path (expand-file-name "site-lisp/" user-emacs-directory))
+
+  (unless (package-installed-p 'use-package)
+    (package-refresh-contents)
+    (package-install 'use-package))
+  (eval-and-compile
+    (setq use-package-always-ensure t
+         use-package-expand-minimally t))
 #+end_src

 * OS-specific Configuration
@@ -341,8 +348,8 @@ won't capture any modifications to =$PATH=, typically handled in a file like
 #+begin_src emacs-lisp
   (when (eq system-type 'darwin)
     ;; Uncomment this if we can't install Hack Nerd font
-    ;; (set-face-attribute 'default nil :font "Menlo-14")
-    (set-face-attribute 'default nil :font "Hack Nerd Font Mono-13")
+    (set-face-attribute 'default nil :font "Menlo-14")
+    ;; (set-face-attribute 'default nil :font "Hack Nerd Font Mono-13")
     (setq exec-path-from-shell-arguments '("-l"))
     (exec-path-from-shell-initialize))
 #+end_src
@@ -1791,9 +1798,9 @@ they don't already exist under =/usr/local/lib/= or =~/.local/lib=.  In case of
 latter, I just add extra paths to =treesit-extra-load-path= explicitly.

 #+begin_src emacs-lisp
-  (when (boundp 'treesit-extra-load-path)
-    (add-to-list 'treesit-extra-load-path "/usr/local/lib/")
-    (add-to-list 'treesit-extra-load-path "~/.local/lib/"))
+ ;; (when (boundp 'treesit-extra-load-path)
+ ;;   (add-to-list 'treesit-extra-load-path "/usr/local/lib/")
+ ;;   (add-to-list 'treesit-extra-load-path "~/.local/lib/"))
 #+end_src

**Comment by KnutUH** [comment]
Reading more blogg post and then I see that use-package is in emacs 29... so all my problems were related to my emacs 28. Sorry for the noise.

**Comment by renzmann** [comment]
Hey, thanks!  Good to know there are people out there reading and using this; that'll motivate me to keep it as clean as I can.  FWIW there's an `emacs-28` branch I keep around in case I need it
